name: Release on Main Branch Change

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get previous version
        id: get-previous-version
        run: |
          echo "previous_version=$(git show HEAD~1:package.json | jq -r .version)" >> $GITHUB_STATE/previous_version.env

      - name: Get current version
        id: get-current-version
        run: |
          echo "current_version=$(node -pe "require('./package.json').version")" >> $GITHUB_STATE/current_version.env

      - name: Check if version is incremented
        id: check-version
        run: |
          previous_version=$(cat $GITHUB_STATE/previous_version.env)
          current_version=$(cat $GITHUB_STATE/current_version.env)
          if [[ "$previous_version" == "$current_version" ]]; then
            echo "version_incremented=false" >> $GITHUB_ENV
          else
            echo "version_incremented=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.get-current-version.outputs.current_version }}
          release_name: Release ${{ steps.get-current-version.outputs.current_version }}
          body: |
            Release ${{ steps.get-current-version.outputs.current_version }}
          draft: false
          prerelease: false
